"""
Report Generator — produces PDF and Excel reports from analysis results.

PDF: uses fpdf2 (pure Python, MIT licence, no system dependencies).
Excel: uses openpyxl (already a project dependency).

Both formats are returned as bytes suitable for st.download_button().
"""

from __future__ import annotations

import io
from datetime import datetime
from typing import List, Optional

import pandas as pd
from loguru import logger

from ..kpi.engine import KPIResult
from ..schema.detector import SchemaProfile


# ── PDF Generator ─────────────────────────────────────────────────────────────

def generate_pdf_report(
    df: pd.DataFrame,
    schema: SchemaProfile,
    kpi_results: List[KPIResult],
    domain: str,
    filename: str,
    ai_summary: Optional[str] = None,
) -> bytes:
    """
    Build a PDF analytics report and return it as raw bytes.

    Sections:
      1. Header — title, filename, generated date
      2. Dataset overview — rows, columns, missing values
      3. Schema summary — column types table
      4. KPI table — name, column, formatted value, description
      5. AI Summary — Gemini-generated narrative (if provided)

    Args:
        df:          The working DataFrame.
        schema:      SchemaProfile from detect_schema().
        kpi_results: Output from compute_kpis().
        domain:      Detected business domain string.
        filename:    Original uploaded filename.
        ai_summary:  Optional Gemini-generated text block.

    Returns:
        PDF content as bytes for st.download_button().
    """
    try:
        from fpdf import FPDF
    except ImportError:
        logger.error("fpdf2 not installed. Run: pip install fpdf2")
        raise

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    pdf.set_margins(15, 15, 15)

    # ── Header ───────────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(15, 15, 40)
    pdf.cell(0, 12, "Sapienoids Analytics Report", new_x="LMARGIN", new_y="NEXT", align="C")

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, f"File: {filename}  |  Domain: {domain.upper()}  |  "
             f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=True, align="C")
    pdf.ln(6)
    pdf.set_draw_color(200, 200, 200)
    pdf.line(15, pdf.get_y(), 195, pdf.get_y())
    pdf.ln(6)

    # ── Dataset Overview ──────────────────────────────────────────────────────
    _section_header(pdf, "Dataset Overview")
    overview = [
        ("Rows",          f"{schema.row_count:,}"),
        ("Columns",       str(schema.col_count)),
        ("Missing cells", str(df.isnull().sum().sum())),
        ("Duplicate rows",str(int(df.duplicated().sum()))),
        ("Numeric cols",  str(len(schema.numeric_cols))),
        ("Categorical cols", str(len(schema.categorical_cols))),
        ("Temporal cols", str(len(schema.temporal_cols))),
    ]
    _two_col_table(pdf, overview)
    pdf.ln(4)

    # ── Schema Summary ────────────────────────────────────────────────────────
    _section_header(pdf, "Column Schema")
    col_headers = ["Column", "Type", "Role", "Cardinality", "Completeness"]
    col_widths  = [55, 25, 35, 30, 35]
    _table_header(pdf, col_headers, col_widths)
    for col_name, cp in schema.columns.items():
        row = [
            col_name[:28],
            cp.dtype[:12],
            cp.role,
            str(cp.cardinality),
            f"{cp.completeness*100:.1f}%",
        ]
        _table_row(pdf, row, col_widths)
    pdf.ln(4)

    # ── KPI Table ─────────────────────────────────────────────────────────────
    if kpi_results:
        _section_header(pdf, "Key Performance Indicators")
        kpi_headers = ["KPI", "Column", "Value", "Description"]
        kpi_widths  = [40, 35, 30, 75]
        _table_header(pdf, kpi_headers, kpi_widths)
        for r in kpi_results:
            _table_row(pdf, [
                r.name[:22],
                r.column[:18],
                r.formatted_value(),
                r.description[:42],
            ], kpi_widths)
        pdf.ln(4)

    # ── AI Summary ────────────────────────────────────────────────────────────
    if ai_summary:
        _section_header(pdf, "AI-Generated Insights")
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(40, 40, 40)
        pdf.multi_cell(0, 5, ai_summary)
        pdf.ln(4)

    # ── Footer ────────────────────────────────────────────────────────────────
    pdf.set_y(-15)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(150, 150, 150)
    # Helvetica is a Latin-1 font — avoid Unicode symbols like (TM) in footer
    pdf.cell(0, 6, "Generated by Sapienoids (TM) Analytics Portal", align="C")

    return bytes(pdf.output())


# ── Excel Generator ───────────────────────────────────────────────────────────

def generate_excel_report(
    df: pd.DataFrame,
    schema: SchemaProfile,
    kpi_results: List[KPIResult],
    domain: str,
    filename: str,
) -> bytes:
    """
    Build a multi-sheet Excel report and return it as raw bytes.

    Sheets:
      Data        — the full working dataset
      KPIs        — computed KPI table
      Schema      — column profile table
      Summary     — dataset overview stats

    Args:
        df:          The working DataFrame.
        schema:      SchemaProfile from detect_schema().
        kpi_results: Output from compute_kpis().
        domain:      Detected business domain string.
        filename:    Original uploaded filename (used in Summary sheet).

    Returns:
        Excel (.xlsx) content as bytes for st.download_button().
    """
    buf = io.BytesIO()
    with pd.ExcelWriter(buf, engine="openpyxl") as writer:
        # Sheet 1: Raw data
        df.to_excel(writer, sheet_name="Data", index=False)

        # Sheet 2: KPIs
        if kpi_results:
            kpi_rows = [r.to_dict() for r in kpi_results]
            kpi_df   = pd.DataFrame(kpi_rows)[["name", "column", "formatted", "description"]]
            kpi_df.columns = ["KPI Name", "Column", "Value", "Description"]
            kpi_df.to_excel(writer, sheet_name="KPIs", index=False)

        # Sheet 3: Schema
        schema_rows = []
        for col_name, cp in schema.columns.items():
            schema_rows.append({
                "Column":       col_name,
                "Dtype":        cp.dtype,
                "Role":         cp.role,
                "Cardinality":  cp.cardinality,
                "Completeness": f"{cp.completeness*100:.1f}%",
                "Null Count":   cp.null_count,
                "Min":          cp.min_val,
                "Max":          cp.max_val,
                "Mean":         cp.mean_val,
            })
        pd.DataFrame(schema_rows).to_excel(writer, sheet_name="Schema", index=False)

        # Sheet 4: Summary
        summary = pd.DataFrame({
            "Metric": ["File", "Domain", "Generated", "Rows", "Columns",
                       "Missing cells", "Duplicate rows"],
            "Value": [
                filename, domain.upper(),
                datetime.now().strftime("%Y-%m-%d %H:%M"),
                f"{schema.row_count:,}", schema.col_count,
                df.isnull().sum().sum(), int(df.duplicated().sum()),
            ],
        })
        summary.to_excel(writer, sheet_name="Summary", index=False)

    return buf.getvalue()


# ── Private helpers ───────────────────────────────────────────────────────────

def _section_header(pdf, title: str) -> None:
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(15, 15, 40)
    pdf.cell(0, 8, title, ln=True)
    pdf.set_draw_color(80, 80, 200)
    pdf.line(15, pdf.get_y(), 195, pdf.get_y())
    pdf.ln(3)


def _two_col_table(pdf, rows: list) -> None:
    pdf.set_font("Helvetica", "", 9)
    for label, value in rows:
        pdf.set_text_color(80, 80, 80)
        pdf.cell(60, 6, label + ":", border=0)
        pdf.set_text_color(20, 20, 20)
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(0, 6, str(value), ln=True)
        pdf.set_font("Helvetica", "", 9)


def _table_header(pdf, headers: list, widths: list) -> None:
    pdf.set_fill_color(30, 30, 60)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 8)
    for h, w in zip(headers, widths):
        pdf.cell(w, 7, h, border=1, fill=True)
    pdf.ln()


def _table_row(pdf, row: list, widths: list, fill: bool = False) -> None:
    pdf.set_fill_color(240, 240, 250)
    pdf.set_text_color(30, 30, 30)
    pdf.set_font("Helvetica", "", 8)
    for val, w in zip(row, widths):
        pdf.cell(w, 6, str(val), border=1, fill=fill)
    pdf.ln()
